# Generated by Django 5.2 on 2025-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gra', 'Gra'), ('quiz', 'Quiz'), ('audiobook', 'Audiobook'), ('plyta', 'Płyta muzyczna')], default='gra', max_length=20),
        ),
    ]
