# Generated by Django 5.2 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='nowe', max_length=20),
        ),
    ]
