# Generated by Django 5.2 on 2025-06-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_downloadable_file_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='downloadable_file',
        ),
        migrations.AddField(
            model_name='product',
            name='downloadable_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
