# Generated by Django 5.2 on 2025-07-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_downloadable_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='custom_form',
            field=models.ForeignKey(blank=True, help_text='Formularz do personalizacji, który klient zobaczy w swoim panelu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customform'),
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Tekst'), ('textarea', 'Wielowierszowy tekst'), ('file', 'Plik (upload)')], max_length=20)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='store.customform')),
            ],
        ),
    ]
