# Generated by Django 5.2 on 2025-07-01 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customform_product_custom_form_customformfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shipping_street', models.CharField(blank=True, max_length=255)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_country', models.CharField(blank=True, default='Polska', max_length=100)),
                ('want_invoice', models.BooleanField(default=False)),
                ('invoice_name', models.CharField(blank=True, max_length=255)),
                ('invoice_nip', models.CharField(blank=True, max_length=20)),
                ('same_as_shipping', models.BooleanField(default=True)),
                ('invoice_street', models.CharField(blank=True, max_length=255)),
                ('invoice_postcode', models.CharField(blank=True, max_length=20)),
                ('invoice_city', models.CharField(blank=True, max_length=100)),
                ('invoice_country', models.CharField(blank=True, default='Polska', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
