# Generated by Django 5.2 on 2025-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ready_file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
