# Generated by Django 5.2 on 2025-07-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_ready_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Link docelowy')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('selected_for_card', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='store.orderitem')),
            ],
        ),
    ]
