# Generated by Django 5.2 on 2025-07-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nowe', 'Nowe'), ('w-trakcie', 'W trakcie realizacji'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='nowe', max_length=20),
        ),
    ]
