# Generated by Django 5.2 on 2025-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
