# Generated by Django 5.2 on 2025-07-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customization_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='custom_files/'),
        ),
    ]
