# Generated by Django 5.2 on 2025-07-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customization_file_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='custom_files/')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='store.customization')),
            ],
        ),
    ]
