# Generated by Django 5.2 on 2025-07-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_customizationfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='file_1',
        ),
    ]
