# Generated by Django 5.2 on 2025-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_customization_file_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='was_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link docelowy'),
        ),
    ]
